// Generated by Wrangler
// This project uses Azure SQL, no D1 bindings needed

/* eslint-disable @typescript-eslint/no-empty-interface */
interface Runtime {}

interface Env {
  // Azure SQL credentials worden via environment variables geladen
  // Zie .env en DEPLOYMENT.md
}
